### ISSUE TITLE
AI TODO List

### ISSUE THREAD

**Issue by calcitem** [calcitem/Sanmill#533]
- [ ] Confirm whether it is possible not to clear the hash table. If not, will endgame have negative effects?
- [ ] AI strength decreases after enabling IDS.
- [ ] Implement Opening Book
